name: cachette
description: A simple and in-memory cache, designed to fulfil the most basic use cases in an elegant way.
version: 1.0.0-dev.1
repository: https://github.com/alexobviously/cachette

environment:
  sdk: ^3.0.0

dependencies:
  elegant: ^0.0.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
