name: cachette
description: A simple and in-memory cache, designed to fulfil the most basic use cases in an elegant way.
version: 0.1.0
repository: https://github.com/alexobviously/cachette

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
